# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(verbose_name='date of issue event')),
                ('event_type', models.CharField(max_length=50)),
                ('event_status_name', models.CharField(max_length=50)),
                ('event_status_jira_id', models.IntegerField()),
                ('event_raw', models.TextField()),
            ],
        ),
    ]
